---
- name: Set the package state based on how python is installed.
  set_fact:
    ansible_package_state: "{{ 'present' if python_install_method == 'package' else 'absent' }}"

# Setup/install tasks.
# - name: Set up python on RedHat.
#   include_tasks: python-setup.RedHat.yml
#   when:
#     - ansible_os_family == 'RedHat'
#     - ansible_distribution != 'Fedora'
#     - python_install_method == 'package'
#
# - name: Set up python on Fedora.
#   include_tasks: python-setup.Fedora.yml
#   when:
#     - ansible_distribution == 'Fedora'
#     - python_install_method == 'package'

- name: Set up python on Ubuntu.
  include_tasks: python-setup/Ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - python_install_method is ('package' or 'build')

# - name: Set up python on Debian.
#   include_tasks: python-setup.Debian.yml
#   when:
#     - ansible_distribution == 'Debian'
#     - python_install_method == 'package'
#
# - name: Set up python using Pip.
#   include_tasks: python-setup.pip.yml
#   when: python_install_method == 'pip'
