---
- name: Converge
  hosts: all
  become: true

  vars:
    python_install_method: pyenv
    python_install_versions: ['python3.9', 'conda']

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
